// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerRoomMonitor.Data;

#nullable disable

namespace ServerRoomMonitor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826145659_SetTemperaturePrecision")]
    partial class SetTemperaturePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerRoomMonitor.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Check1Ok")
                        .HasColumnType("bit");

                    b.Property<bool>("Check2Ok")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOk")
                        .HasColumnType("bit");

                    b.Property<int>("ServerRoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServerRoomId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("ServerRoomMonitor.Models.ServerRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServerRooms");
                });

            modelBuilder.Entity("ServerRoomMonitor.Models.Inspection", b =>
                {
                    b.HasOne("ServerRoomMonitor.Models.ServerRoom", "ServerRoom")
                        .WithMany("Inspections")
                        .HasForeignKey("ServerRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerRoom");
                });

            modelBuilder.Entity("ServerRoomMonitor.Models.ServerRoom", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
